### PR TITLE
Replace most of 'deprecated' wordings

### PR DESCRIPTION
**Pull request by isaak654**
This pull request adds better separation between deprecated, obsolete and removed Sandboxie settings.
Considering that there are many changes, any review would be appreciated.

### CODE REVIEW

**Comment by isaak654** [comment]
@wilders-soccerfan

**Comment by wilders-soccerfan** [comment]
> @wilders-soccerfan

I'm not too familiar with the error messages but the rest looks good. 
In Content/BlockPort.md, is it worth a mention that the example shown  
corresponds to [Template_BlockPorts] in templates.ini?

**Comment by typpos** [comment]
Briefly browsed through the changes without verifying actual content and it looks fine to me.

It would be good to have a "current version only" documentation view so as time goes by, we don't end up with "obsolete" and "removed" feature descriptions cluttering the docs. Once people upgraded their ini, they probably no longer care about legacy features. Regardless, good as is.

**Review by offhub — APPROVED** [review]
Looks good.

**Pull request merged**
