### PR TITLE
Revert "Typo fix(FAQEmail.md) - Approved"

### PR DESCRIPTION
**Pull request by Luro223**
Reverts sandboxie-plus/sandboxie-docs#74

### CODE REVIEW

**Comment by isaak654** [comment]
For what reason? This will only restore the typo.
typo

**Comment by Luro223** [comment]
@isaak654 Many typo issues (none of your email(s) is(are) stored/See (the)answer to (the)previous question and so on)

**Comment by Luro223** [comment]
I worked on this right before you merged, so all my changes were nullified

**Comment by isaak654** [comment]
Then I would advise to create a new PR.

**Comment by isaak654** [comment]
By the way, "none of your email is" seems to be a common expression searchable on Google.

**Comment by isaak654** [comment]
For the record, here there are the unmerged changes: https://github.com/Luro223/sandboxie-docs/commit/1ba72d4db98e437fd83f5475d5c78ae7320f659a

**Pull request closed without merging**
