### PR TITLE
Update security-mode.md

### PR DESCRIPTION
**Pull request by wilders-soccerfan**
Updating the last of the box types in the PlusContent folder available currently (v1.10.5).

### CODE REVIEW

**Comment by isaak654** [comment]
1.  The detailed references to UseRuleSpecificity and DropAdminRights should probably be moved to their own pages: [RuleSpecificity.md](https://github.com/sandboxie-plus/sandboxie-docs/blob/8e7c58eb49e62528884f9ee6b13a898540b2ef3e/PlusContent/RuleSpecificity.md) [DropAdminRights.md](https://github.com/sandboxie-plus/sandboxie-docs/blob/ebb1585b5f89da47131d8ff609923f09cbf28608/Content/DropAdminRights.md), in order to point to those links when needed.
2. About RestrictDevices, SysCallLockDown, UseSecurityMode settings: a decision must be made as to whether they deserve a separate page. What do you think?

**Comment by wilders-soccerfan** [comment]
> 

Item 1 makes sense. Item 2 should probably also include UsePrivacyMode if it is decided to have separate pages.
OT: Thanks for your massive effort in revamping the entire documentation!

**Comment by offhub** [comment]
Each setting should have its own page. This makes it easy to refer to when needed.

**Comment by wilders-soccerfan** [comment]
Agreed. However, I feel that until the pages for these settings get documented by the contributor community, 
updating security-mode.md should retain the relevant context and move forward (or be shelved as a draft request).

**Review by offhub — APPROVED** [review]

**Pull request merged**
